name: build IPA

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Dependencies
        run: npm install

      - name: Install Capacitor iOS
        run: npm install @capacitor/core @capacitor/cli @capacitor/ios

      - name: Add iOS if missing
        run: |
          if [ ! -d "ios" ]; then
            npx cap add ios
          fi

      - name: Sync iOS
        run: npx cap sync ios

      - name: Install Pods
        run: |
          cd ios/App
          pod install

       - name: Build App
        run: |
          cd ios/App
          set -o pipefail
          xcodebuild clean build \
            -workspace App.xcworkspace \
            -scheme App \
            -sdk iphoneos \
            -configuration Release \
            CODE_SIGNING_ALLOWED=NO \
            2>&1 | tee xcodebuild.log

      - name: Upload Build
        uses: actions/upload-artifact@v4
        with:
          name: ios-build
          path: ios
